- name: checking data types
  hosts: localhost
  vars:
    NAME: SIVA
    SKILLS: 
    - DEvops
    - aws
    - python
    - linux
    experience:
      devops: 7
      aws: 6
      python: 8
      linux: 6
    trainer: true
  tasks:
  - name: print keyvalue pair
    ansible.builtin.debug:
      msg: "name: {{NAME}}"
  - name: print map
    ansible.builtin.debug:
      msg: "skills: {{SKILLS}}"    

      

      