- name: variable from play level
  hosts: localhost
  vars:
    course: "devops"
    duration: "3 months"
    trainer: "siva"
  tasks: 
  - name: check variables
    ansible.builtin.debug:
      msg: "hi iamlearnig {{course}}, trainer is {{trainer}} , duration is {{duration}} 

