- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: pls enter usr name
    private: false
  - name: PASSWORD
    prompt: please enter your password
    private: true
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
      msg: "username is: {{username}}"  
     